### ISSUE TITLE
Update to the latest Github color scheme

### ISSUE THREAD

**Issue by ignacy** [philiparvidsson/GitHub-Theme-for-Emacs#13]
Hi there, thanks for creating this theme 👍 

I noticed GitHub did change some settings in its version and now it looks a bit different ![Comare](https://imfilesscreens.s3.amazonaws.com/GitHub-Theme-for-Emacsgithub-theme.el_at_master__philiparvidssonGitHub-Theme-for-Emacs_2017-06-15_10-02-38.png)

It would be cool to have an update, I really like the new colors.

**Comment by philiparvidsson** [comment]
Wow, I hadn't even noticed, when did this change occur? Anyway, I agree with you. I should look into this. I'd consider making a separate branch for it but I think (for the sake of MELPA) it would be wiser to provide it in a separate repository.

**Comment by philiparvidsson** [comment]
https://github.com/philiparvidsson/GitHub-Modern-Theme-for-Emacs

**Comment by ignacy** [comment]
It's awesome 🏆 ❤️  Thanks! You rock!
